#!/bin/bash

echo "=== vex 交互式功能测试 ==="
echo ""
echo "1. 测试 list-remote（可滚动列表）"
echo "   运行: ./target/debug/vex list-remote node"
echo "   - 使用上下箭头键滚动查看所有版本"
echo "   - 按 Ctrl+C 退出"
echo ""
echo "2. 测试交互式安装"
echo "   运行: ./target/debug/vex install node"
echo "   - 会显示版本列表供选择"
echo "   - 使用上下箭头键选择版本"
echo "   - 按回车确认安装"
echo "   - 按 Esc 或 Ctrl+C 取消"
echo ""
echo "3. 测试直接安装（原有功能保留）"
echo "   运行: ./target/debug/vex install node@20.11.0"
echo "   - 直接安装指定版本，无需交互"
echo ""
echo "=== 功能说明 ==="
echo "✅ list-remote: 显示可滚动的版本列表（最多显示20行，可上下滚动）"
echo "✅ install node: 交互式选择版本安装"
echo "✅ install node@20.11.0: 直接安装指定版本"
echo ""
